### ISSUE TITLE
RubyGems release

### ISSUE THREAD

**Issue by CyborgMaster** [jhubert/guard-maven#5]
@jhubert, can we get a new ruby gems release now that my pull request is merged?  Is this something you would like me to do now that you've made me a collaborator?  Do I need publishing rights on RubyGems?

**Comment by CyborgMaster** [comment]
bump

**Comment by CyborgMaster** [comment]
I just added a small new feature for command line args (#6).  I'd like to get a rubygems release out.  @jhubert, can I get authorization to do that?

**Comment by CyborgMaster** [comment]
I just read the docs and found that you'll need my RubyGem's email for that.  It's jeremy.mickelson@gmail.com

**Comment by jhubert** [comment]
@CyborgMaster Done :)

**Comment by CyborgMaster** [comment]
Sweet.  I'll push out a new version now.

**Comment by jhubert** [comment]
Great! Thanks for taking care of that. :smiley:

**Comment by CyborgMaster** [comment]
Awesome.  Version 0.3.0 released.  Thanks again!
